name: Docker build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get/set tag from github env var
      run: echo ::set-env name=TAG::${GITHUB_REF##*/}
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Run Buildx
      run: |
       docker buildx build \
          --platform linux/arm/v6,linux/arm/v7,linux/arm64 \
          -t duczen/octoprint:$TAG \
          -t duczen/octoprint:latest \
          .
    - name: Publish docker image
      run: |
        docker login --username ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push duczen/octoprint:$TAG
        docker push duczen/octoprint:latest
