name: Docker build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: docker buildx (arm) and push
      run: |
        TAG=$(echo $GITHUB_REF | cut -d '/' -f 3)
        docker login --username ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker buildx build \
          --platform linux/arm/v6,linux/arm/v7,linux/arm64 \
          --push \
          -t duczen/octoprint:$TAG \
          -t duczen/octoprint:latest \
          .
