name: Docker build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
    - name: Run Buildx
      run: |
       docker buildx build \
          --platform linux/arm/v6,linux/arm/v7,linux/arm64 \
          -t duczen/octoprint:latest .
    - name: Publish docker image
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push duczen/octoprint:latest
